name: schedule job

on:
  schedule:
    - cron: "38 12 * * *"   # runs every day at 12:24 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "workflow executed"
