name: schedule job

on:
  schedule:
    - cron: "51 19 * * *"   # Runs every day at 12:51 AM PKT (07:51 PM UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "workflow executed"
